### ISSUE TITLE
The latest SD2_Image in the pacman packages is broken

### ISSUE THREAD

**Issue by sacredbanana** [devkitPro/pacman-packages#108]
Ever since SDL2_Image was updated in the pacman packages I have been unable to get my switch game which uses that library to build. I've had to build from my other PC which still has the old version of SDL2_Image

I get a linker error when trying to build with the new SDL2_image:

/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/portlibs/switch/lib/libSDL2_image.a(IMG_webp.o): in function `IMG_InitWEBP':
IMG_webp.c:(.text.IMG_InitWEBP+0x10): undefined reference to `WebPGetFeaturesInternal'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld: IMG_webp.c:(.text.IMG_InitWEBP+0x14): undefined reference to `WebPDecodeRGBInto'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld: IMG_webp.c:(.text.IMG_InitWEBP+0x18): undefined reference to `WebPDecodeRGBAInto'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld: IMG_webp.c:(.text.IMG_InitWEBP+0x1c): undefined reference to `WebPGetFeaturesInternal'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld: IMG_webp.c:(.text.IMG_InitWEBP+0x20): undefined reference to `WebPDecodeRGBInto'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld: IMG_webp.c:(.text.IMG_InitWEBP+0x24): undefined reference to `WebPDecodeRGBAInto'
collect2: error: ld returned 1 exit status

**Comment by fincs** [comment]
It's not broken. It's just that webp is now required as a dependency. Can you post the LIBS section of your makefile? You shouldn't be having problems if you use pkgconfig to lift the list of needed dependencies.

**Comment by sacredbanana** [comment]
The libs section in the makefile is as follows:

LIBS	:= -lSDL2_image -lglapi -ljpeg `sdl2-config --libs` `freetype-config --libs` -lnx

**Comment by fincs** [comment]
Try this:

```makefile
LIBS := `aarch64-none-elf-pkg-config SDL2_ttf SDL2_image SDL2_gfx --libs`
```

**Comment by sacredbanana** [comment]
Thank you very much for your help. It's now building. I didn't know about pkg-config

**Comment by Waifro** [comment]
i have still the same problem. I have done what  WinterMute said, but i can get it to working. Btw, this is my first fresh install using pacman installer for Windows. The libs are the same from your respond, but same error prints out.

**Comment by WinterMute** [comment]
@Waifro are you referring to another issue? I haven't commented here.

If you do have the same issue then what @fincs suggested with 
```makefile
LIBS := `aarch64-none-elf-pkg-config SDL2_ttf SDL2_image SDL2_gfx --libs`
```

should work.

**Comment by Waifro** [comment]
Oh you are right! Sorry WinterMute, i mistaken you with fincs 😅

Yeah, those are the same libs i used, but he didnt wont to compile. For now, im using somebody's makefile, but thats not what i want. I also tried to put `-lwebp` on it, but new errors pops out...
