### ISSUE TITLE
Broken libxmp packages

### ISSUE THREAD

**Issue by knight-ryu12** [devkitPro/pacman-packages#112]
seems like #104 pkgbuild ships with wrongly linked thing, therefore it ships broken packages.
:cry: 
The things, (That I am not quite sure+ speculation), is ./configure is not being good to detect on it.

**Comment by knight-ryu12** [comment]
Error
```
arm-none-eabi-gcc -MMD -MP -MF /home/io/Desktop/3ds-tuneplayer/build/fshelper.d -g -Wall -O3 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -I/home/io/Desktop/3ds-tuneplayer/include -I/opt/devkitpro/libctru/include -I/opt/devkitpro/portlibs/3ds/include -I/home/io/Desktop/3ds-tuneplayer/build -DARM11 -D_3DS -std=gnu11 -c /home/io/Desktop/3ds-tuneplayer/source/fshelper.c -o fshelper.o 
linking 3ds-tuneplayer.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/portlibs/3ds/lib/libxmp.a(load.o): in function `execute_command':
load.c:(.text.execute_command+0x2c): undefined reference to `popen'
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld: load.c:(.text.execute_command+0x6c): undefined reference to `pclose'
collect2: error: ld returned 1 exit status
```

**Comment by joel16** [comment]
Can also confirm I get this issue:

```linking application.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/portlibs/3ds/lib/libxmp.a(load.o): in function `execute_command':
load.c:(.text.execute_command+0x2c): undefined reference to `popen'
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld: load.c:(.text.execute_command+0x6c): undefined reference to `pclose'
collect2: error: ld returned 1 exit status
/opt/devkitpro/devkitARM/3ds_rules:41: recipe for target '/home/joel16/3ds/application/application.elf' failed
make[1]: *** [/home/joel16/3ds/application/application.elf] Error 1
Makefile:216: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by WinterMute** [comment]
random people turning up to confirm issues aren't helpful. They just create unnecessary noise in the issue tracker.

**Comment by knight-ryu12** [comment]
can we keep civil here? I'd think this is intense and I don't want any of this. can we get back in topic without any of this happened?

**Comment by WinterMute** [comment]
The problem is that libxmp, like many other open source packages, is written as though windows and unix compatible systems are the only systems that exist. I've added a patch to disable the use of external helpers when the popen tests fail which should hopefully help. https://github.com/devkitPro/pacman-packages/commit/e545cdbe7621eeb4dfda363da425c824f38957da

I suppose I should have realised that you hadn't tested the package you PR'd when I had to fix it before packaging - https://github.com/devkitPro/pacman-packages/commit/9dac92f6215884ae358cb757ab601d1746c41fd6
