### ISSUE TITLE
switch-zstd missing dependencies

### ISSUE THREAD

**Issue by Denkishi** [devkitPro/pacman-packages#129]
![Screenshot_2020-03-15_16-38-57](https://user-images.githubusercontent.com/20754887/76712191-9bdb3f80-6716-11ea-897a-cc778900e9e4.png)

this is what i get while trying to use makepkg on the pkgbuild file for switch-zstd, i have all the dependencies listed as missing

**Comment by WinterMute** [comment]
`sudo pacman -S switch-zstd` works ...
