### ISSUE TITLE
3ds-curl not working for ftp URLs

### ISSUE THREAD

**Issue by badda71** [devkitPro/pacman-packages#130]
The current version of 3ds-curl will always exit with "select/poll error" when trying to download ftp urls. This can be fixed by removing "#define HAVE_POLL_FINE 1" in file lib/curl_config.h, line 540 after executing ./configure and before executing make.
Seems like the poll() implementation is buggy on the 3DS and curl should rather rely on select().

**Comment by fincs** [comment]
On 3DS, we implement select with poll, so switching that up would accomplish nothing (if all, it would make it worse).

**Comment by badda71** [comment]
Ok, so the define HAVE_POLL_FINE breaks something else on the 3DS. Anyways, getting rid of this define fixes curl for ftp URLs

**Comment by badda71** [comment]
Just opened a PR: https://github.com/devkitPro/pacman-packages/pull/131

**Comment by WinterMute** [comment]
This is working with latest libs.
