### ISSUE TITLE
Switch SDL 2.0.12 fails to build with CMake (patch avalible)

### ISSUE THREAD

**Issue by AJenbo** [devkitPro/pacman-packages#143]
It appears that ~~Devkit-pro~~ the switch SDL2 package is also affected by the broken CMake rule in SDL 2.0.12 since it was [updated](https://github.com/devkitPro/pacman-packages/commit/f4a071c99e1827917747630dbc420c33effd00ad#diff-debbdb4b70712bf95a0b2ca62209fd45):
https://bugzilla.libsdl.org/show_bug.cgi?id=5039

A patch was already made that has been verified to fix this issue for macOS: https://hg.libsdl.org/SDL/rev/60f1e9fb5957

This is currently preventing DevilutionX from building for Switch: https://github.com/diasurgical/devilutionX/issues/719

**Comment by AJenbo** [comment]
@WinterMute let me know if there is any info, or other things, that I can provideo to help this along.

**Comment by WinterMute** [comment]
A small testcase illustrating the issue would help a lot in verifying the problem and any potential fix. Large projects aren't at all helpful for this kind of thing.

**Comment by rsn8887** [comment]
I think a test case is not needed because there’s already a known fix, just needs to be merged I think. Just like @AJenbo said this should fix it https://hg.libsdl.org/SDL/rev/60f1e9fb5957

**Comment by rsn8887** [comment]
Never mind that patch doesn't work.

The SHARED_LIBRARY_SUFFIX is still .so on Switch, but there are no shared libraries.

Manually setting it to .a works.

**Comment by rsn8887** [comment]
I found a way to get it to work.

Just replace 
```
find_package(SDL2 CONFIG QUIET)
```
with
```
find_package(SDL2_STATIC CONFIG QUIET)
```
on Switch for force static SDL2.

**Comment by WinterMute** [comment]
> I think a test case is not needed because there’s already a known fix, just needs to be merged I think.

Which, as you found, wasn't a fix. This is why I asked for a testcase.

We need to provide an official cmake toolchain file to solve this I think. Projects supplying their own isn't really sustainable.

**Comment by AJenbo** [comment]
It's possible, we have done some work recently to rely on pkg-config by default and instead provide workarounds for platforms where they are missing or invalid
