### ISSUE TITLE
3ds-libarchive: Issues with extracting some archives.

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [devkitPro/pacman-packages#155]
Hello! 3ds-libarchive seems to have issues by extracting some archives. It seems like, the used 3ds-libarchive is from 2013, which is pretty old. I'm not able to properly build a portlib for it, so I thought I'd report it here. Maybe libarchive v3.4.3 is able to fix these issues? I'm not sure, tbh. It would be great, when 3ds-libarchive would get an update. :) Thanks in advance!

**Comment by WinterMute** [comment]
No support will be provided for pirate tools here, sorry.
