### ISSUE TITLE
switchvars.sh script doesn't work with zsh shell

### ISSUE THREAD

**Issue by gnaghi** [devkitPro/pacman-packages#166]
BASH_SOURCE variable is specific to bash.
${DEVKITPRO} can be used instead, as the script switchvars is located at the root folder of devkitpro.
Or, a trick like this one https://gist.github.com/elentok/5546958 can be used.

**Comment by dezza** [comment]
https://stackoverflow.com/questions/29832037/how-to-get-script-directory-in-posix-sh
Read "How to handle sourced invocations", its a tricky problem that can't be handled well universally, without being longer than the actual script

For me it makes better sense to just use `bash switchvars.sh`. Who doesn't keep bash for compatability in most cases? Even tmux relies on it for its plugins/scripts

**Comment by WinterMute** [comment]
The scripts in question are intended primarily for use when building and packaging portlibs or porting autotools based projects where bash tends to be a necessity. They're not really intended for general use. Mostly we recommend use of the template Makefiles for switch homebrew.
