### ISSUE TITLE
arm-none-eabi-gdb immediately exits with code 127 (MSYS2 x86_64)

### ISSUE THREAD

**Issue by AliceLR** [devkitPro/pacman-packages#199]
Attempting to start arm-none-eabi-gdb (from devkitARM-gdb 9.2-4) in Windows results in no console output and the return code 127.
```
$ arm-none-eabi-gdb --help; echo $?
127
```

The copy of arm-none-eabi-gdb packaged with devkitARM-r53 works as expected (I don't have any newer devkitARM gdb versions to test in my pacman cache).
```
$ arm-none-eabi-gdb --help; echo $?
This is the GNU debugger.  Usage:

    gdb [options] [executable-file [core-file or process-id]]
    gdb [options] --args executable-file [inferior-arguments ...]
...
0
```

**Comment by fincs** [comment]
Certain DLLs must be on PATH for binaries to be runnable on Windows - try adding c:\devkitPro\tools\bin to the front of the PATH environment variable.

**Comment by AliceLR** [comment]
`PATH="$DEVKITPRO/tools/bin:$PATH" arm-none-eabi-gdb` does seem to do the trick. Looks like `libstdc++-6.dll` is the problem.
```
$ ntldd /opt/devkitpro/devkitarm/bin/arm-none-eabi-gdb
        libgcc_s_seh-1.dll => C:\msys64\mingw64\bin\libgcc_s_seh-1.dll (0x0000000000720000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000e50000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000e50000)
        libwinpthread-1.dll => C:\msys64\opt\devkitpro\devkitarm\bin\libwinpthread-1.dll (0x0000000000e50000)
        libstdc++-6.dll => C:\msys64\mingw64\bin\libstdc++-6.dll (0x0000000000e50000)
        USER32.dll => C:\WINDOWS\SYSTEM32\USER32.dll (0x0000000000e50000)
        WS2_32.dll => C:\WINDOWS\SYSTEM32\WS2_32.dll (0x00000000016e0000)
```

**Comment by fincs** [comment]
Glad the problem is solved. Fwiw we officially support adding said directory to PATH (in fact we do so on Linux/MacOS by default since it contains useful tools people might want to use).

**Comment by AliceLR** [comment]
I do keep `$DEVKITPRO/tools/bin` on my PATH, but generally after `/mingw64/bin`. I'll keep that in mind.
