### ISSUE TITLE
dkp-osx devkitARM r55 available?

### ISSUE THREAD

**Issue by GriffinRichards** [devkitPro/pacman-packages#211]
I seem to be unable to get devkitARM r55 on macOS 10.13.
`sudo dkp-pacman -Syu` tells me that dkp-osx is up to date, and `sudo dkp-pacman -Sl` shows me that I have `devkitARM r54-3` installed. Is r55 not available for dkp-osx?

**Comment by WinterMute** [comment]
Make sure you have the latest devkitpro pacman installed see https://github.com/devkitPro/pacman/releases/latest then try again.
