### ISSUE TITLE
multiple devkitA64 cmake files

### ISSUE THREAD

**Issue by Jan200101** [devkitPro/pacman-packages#226]
https://github.com/devkitPro/pacman-packages/commit/a8e7d24f89274a0d8377ce964f9a1776acc52ccb introduced switch-cmake which provides files to allow the usage of devkitA64 with cmake projects

but slightly different cmake files have already existed in the devkitpro-pkgbuild-helpers package ([pkgbuild-scripts](https://github.com/devkitPro/pacman-packages/tree/master/pkgbuild-scripts)) with the devkitA64.cmake and switch.cmake files existing since at least 2018

What is the problem here?
Was pkgbuild-scripts forgotten about?
Were the cmake files copied into a new package to remove the need to install them for every toolchain?
Was it done for backwards compatibility? (even if so why not make pkgbuild-scripts depend on switch-cmake)

**Comment by WinterMute** [comment]
pkgbuild-scripts was never intended for general use and the functionality found there is now being split across multiple packages to try and address the problem with multiple projects with multiple versions of dysfunctional cmake machinery. The goal is to get things standardized.

**Comment by Jan200101** [comment]
> pkgbuild-scripts was never intended for general use and the functionality found there is now being split across multiple packages [...]

Fair point and to be honest it should never have been like that from the start
I do not know why you only now made the change, it should have been made back in 2018

> [...] to try and address the problem with multiple projects with multiple versions of dysfunctional cmake machinery. The goal is to get things standardized.

Having worked with other homebrew toolchains in the past (most notably VitaSDK) I do not see why you are making such a big fuss about it
cmake has a lot of issues, that is true
but it simplifies things like cross compilation for a toochain packager more than a build system like Makefiles


> This is an issue tracker, not a forum. Please don't ask random questions here.

This is an issue
you are inherently providing multiple different cmake files without pointing people at the one you want people using
and with time these will drift apart from each other resulting in possibly undesired behavior

The fact you don't even see the issue tells me that the package repository is very disorganized

and to add upon that
multiple times you have made displayed that you dislike cmake

> We still hate cmake [...]

> [...] dysfunctional cmake machinery.

If you hate it so much don't create terrible infrastructure for it in the first place and let developers figure it out, meson, cmake, waf, etc. already are well documented in regards to cross compilation and any special information can be gathered from official DKP Makefiles

**Comment by WinterMute** [comment]
People will be pointed at the desired cmake files when the desired cmake files are provided and ready for general consumption. I have neither the time nor the energy to get into a protracted discussion about the merits of various buildsystem generators.

devkitPro has a long history of providing toolchains for homebrew developers, long before 2018. We're not the ones creating terrible infrastructure.
