### ISSUE TITLE
Problem on MacOS with endian.h

### ISSUE THREAD

**Issue by PoloNX** [devkitPro/pacman-packages#230]
I install the package sdl2-switch but when I want use it in vscode, endian.h is not here. In the SDL_Endian.h you have to replace 
#include <endian.h>
to 
#include <machine.endian.h>

**Comment by fincs** [comment]
VSCode's C/C++ extension is known for being quite difficult to set up for cross compilation, as it assumes that your project is targetting your host computer. Even though we don't really provide support for any specific IDEs, I can suggest you set the property `compilerPath` in the configuration you're using inside c_cpp_properties.json to point to devkitA64 itself (`/opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++`), as well as `intelliSenseMode` to `gcc-arm64`. That should at least fix the system include paths and defines.
