### ISSUE TITLE
freetype2 doesn't get recognized

### ISSUE THREAD

**Issue by MrSwedish** [devkitPro/pacman-packages#235]
hi, when trying to build https://github.com/saucesaft/xash3d-wii it fails with
```
Checking for 'freetype2'                                : yes
Checking for 'freetype2' sanity                         : no
freetype2 isn't installed correctly. Make sure you installed proper development package for target architecture
```
even though i have installed ppc-freetype
(github says build fails but thats because they don't tell it to install ~~devkit pro~~ **devkitPPC** at all) _note: devkitPro is an organisation that provides toolchains and libraries, we are not something you install_

**Comment by MrSwedish** [comment]
maybe pull request https://github.com/devkitPro/pacman-packages/pull/219 could fix it

**Comment by WinterMute** [comment]
I'm not familiar with waf unfortunately. Unless you have a log saying what the actual failure is then we can't really be of assistance, sorry.

**Comment by MrSwedish** [comment]
alright
