### ISSUE TITLE
The switch cmake toolchain does not respect the output name properties of targets

### ISSUE THREAD

**Issue by madebr** [devkitPro/pacman-packages#238]
When a cmake project changes the [`OUTPUT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/OUTPUT_NAME.html) property of a target or sets [`CMAKE_EXECUTABLE_SUFFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_EXECUTABLE_SUFFIX.html), the `nx_generate_nacp` and `nx_create_nro` functions don't work anymore.

Example the following project:
**CMakeLists.txt**
```cmake
cmake_minimum_required(VERSION 3.8)
project(alt_name)

add_executable(exe exe.c)

# Either one of the following makes this project fail to build
set_property(TARGET exe PROPERTY OUTPUT_NAME "awesome_exe")
set(CMAKE_EXECUTABLE_SUFFIX ".elf")

nx_generate_nacp(awesome.nacp NAME exe)
nx_create_nro(exe NACP awesome.nacp)
```

**exe.c**
```c
int main() {
	return 0;
}
```

Using the `devkitpro/devkita64` docker image, building the project fails with the following error:

```
[ 75%] Generating awesome.nacp
/opt/devkitpro/tools/bin/nacptool --create exe "Unspecified Author" 1.0.0 awesome.nacp
[100%] Generating exe.nro
/opt/devkitpro/tools/bin/elf2nro exe exe.nro --icon=/opt/devkitpro/libnx/default_icon.jpg --nacp=awesome.nacp
Failed to open input!
```

The error occurs because the cmake toolchain assumes the output filename is the same as the target name.

I can fix this by applying the following patch:
```patch
--- /opt/devkitpro/cmake/Switch.cmake	2021-06-14 10:23:20.000000000 +0000
+++ ../Switch.cmake	2021-06-22 16:11:14.049765329 +0000
@@ -81,16 +81,19 @@
 
 	add_custom_command(
 		OUTPUT "${outfile}"
-		COMMAND "${NX_NACPTOOL_EXE}" --create "${NACP_NAME}" "${NACP_AUTHOR}" "${NACP_VERSION}" "${outfile}"
+		COMMAND "${NX_NACPTOOL_EXE}" --create "$<TARGET_FILE:${NACP_NAME}>" "${NACP_AUTHOR}" "${NACP_VERSION}" "${outfile}"
+		DEPENDS ${NACP_NAME}
 		VERBATIM
 	)
 endfunction()
 
-function(nx_create_nro prefix)
+function(nx_create_nro target)
 	cmake_parse_arguments(ELF2NRO "NOICON;NONACP" "ICON;NACP;ROMFS" "" ${ARGN})
 
-	set(ELF2NRO_ARGS ${prefix} "${prefix}.nro")
-	set(ELF2NRO_DEPS ${prefix})
+	get_target_property(TARGET_OUTPUT_NAME ${target} OUTPUT_NAME)
+
+	set(ELF2NRO_ARGS "$<TARGET_FILE:${target}>" "${TARGET_OUTPUT_NAME}.nro")
+	set(ELF2NRO_DEPS ${target})
 
 	if (DEFINED ELF2NRO_ICON AND ELF2NRO_NOICON)
 		message(FATAL_ERROR "nx_create_nro: cannot specify ICON and NOICON at the same time")
@@ -105,7 +108,7 @@
 	endif()
 
 	if (NOT DEFINED ELF2NRO_NACP AND NOT ELF2NRO_NONACP)
-		set(ELF2NRO_NACP "${prefix}.default.nacp")
+		set(ELF2NRO_NACP "${target}.default.nacp")
 		nx_generate_nacp(${ELF2NRO_NACP})
 	endif()
 
@@ -139,15 +142,15 @@
 	endif()
 
 	add_custom_command(
-		OUTPUT "${prefix}.nro"
+		OUTPUT "${TARGET_OUTPUT_NAME}.nro"
 		COMMAND "${NX_ELF2NRO_EXE}" ${ELF2NRO_ARGS}
 		DEPENDS ${ELF2NRO_DEPS}
 		VERBATIM
 	)
 
 	add_custom_target(
-		"${prefix}_nro" ALL
-		DEPENDS "${prefix}.nro"
+		"${target}_nro" ALL
+		DEPENDS "${TARGET_OUTPUT_NAME}.nro"
 	)
 endfunction()
 
```

When building the project above, `awesome_exe.elf`, `awesome_exe.nro` and `awesome.nacp` are generated.

**Comment by fincs** [comment]
> ```
> get_target_property(TARGET_OUTPUT_NAME ${target} OUTPUT_NAME)
> ```

What happens if OUTPUT_NAME isn't set, or is set *after* calling nx_create_nro? I recall at some point I was trying to read a target's `OUTPUT_NAME` with `get_target_property` and it was blank by default. I expect some more generator expression magic to be necessary in order to fix this properly.

**Comment by madebr** [comment]
Good catch.
`TARGET_OUTPUT_NAME-NOTFOUND` is assigned to the variable instead.

Since`TARGET_OUTPUT_NAME` variable is only used for constructing the nro output file, adding
```cmake
    if(NOT TARGET_OUTPUT_NAME)
        set(TARGET_OUTPUT_NAME "${target}")
    endif()
```
fixes it.
A cmake generator expression is used to refer to the actual created target file in the argument list (`$<TARGET_FILE:${target}>`)

**Comment by madebr** [comment]
I've opened a pr so you can test it locally. See #239
