### ISSUE TITLE
What about NES and SNES?

### ISSUE THREAD

**Issue by busterbeam** [devkitPro/pacman-packages#250]
Doesn't anyone not want to build games for those consoles?  No demand hence no package?

**Comment by picobelloo** [comment]
Sorry for hijacking this issue, but new issues [seem](https://archive.md/fQERq) to be [malfunctioning](https://github.com/devkitPro/pacman-packages/issues/257) for some odd reason, and I've found no other method of contacting the maintainers...

A year or two ago there used to be a repository on this github organization called [tool-packages](https://github.com/devkitPro/tool-packages), hosting PKGBUILDs for everything in the `dkp-<os>` repositories, including base toolchains and assorted tools such as hactool.
I'm wondering, what happened? Can these PKGBUILDs still be found anywhere?

**Comment by WinterMute** [comment]
We can't provide support for every console people might want to make games for. Currently we only provide gcc based toolchains so NES & SNES support are unlikely.
