### ISSUE TITLE
cURL not working, having timeout on name lookup

### ISSUE THREAD

**Issue by Kry-a** [devkitPro/pacman-packages#261]
# Problem
I've been trying to get cURL to work for a while now to use an API, but have no idea how to go about doing that.

I'm trying to use `curl_easy`, which *does seem to work* on a Windows 11 install.
However when executed inside the 3DS, it just seems to return `6` or `7` status code.
And enabling verbose mode curl prints `* timeout on name lookup is not supported`.

# What I've tried

I even tried just downloading a simple [file from github](https://raw.githubusercontent.com/devkitPro/pacman-packages/master/3ds/curl/.gitignore), but it just refuses to work.

I've tried looking at code from elsewhere as an example, but I can't seem to get it work.

# Sample of code

Versions:
`cURL/7.69.1-1`
`libctru/2.1.0-1`

```cpp
curl_easy_setopt(getTime, CURLOPT_URL, "time.nist.gov");
curl_easy_setopt(getTime, CURLOPT_PORT, 13L);
curl_easy_setopt(getTime, CURLOPT_SSL_VERIFYPEER, 0L);
curl_easy_setopt(getTime, CURLOPT_VERBOSE, 1L);
curl_easy_setopt(getTime, CURLOPT_STDERR, stdout);
curl_easy_setopt(getTime, CURLOPT_HTTP09_ALLOWED, 1L);
curl_easy_setopt(getTime, CURLOPT_WRITEFUNCTION, timeWriteCallback);

curl_easy_perform(getTime);
curl_easy_cleanup(getTime);
```

**Comment by WinterMute** [comment]
Apologies for not seeing this issue sooner.

Your problem is that you haven't initialised the network on the 3DS. See this section in the sockets example https://github.com/devkitPro/3ds-examples/blob/master/network/sockets/source/sockets.c#L70-L84
