### ISSUE TITLE
devkitA64 missing from devkit-env.sh

### ISSUE THREAD

**Issue by kenballus** [devkitPro/pacman-packages#264]
Not sure if this is the right place to report this, but installing the switch-dev metapackage does not add /opt/devkitpro/devkitA64/bin to the path in /etc/profile.d/devkit-env.sh

**Comment by fincs** [comment]
This is intentional, in order to avoid conflicts with other GCC based toolchains that may be installed in the system. Individual toolchain bin folders should never be permanently added to PATH.
