### ISSUE TITLE
wii-sdl_image is compiled without image support

### ISSUE THREAD

**Issue by Anthypatos** [devkitPro/pacman-packages#287]
It seems like wii-sdl_image is being compiled [here](https://github.com/devkitPro/pacman-packages/blob/10a4fbad6c14a32ae25ab645a4e2951240cf9b1f/wii/SDL_image/PKGBUILD#L35) without image support of any kind. This is needed in order to initialise support for different file formats.

For instance, when trying to initialise JPEG support using `IMG_Init(IMG_INIT_JPG)` the return value is 0, which indicates an error in the initialisation. In addition, the following error string is set and can be retrieved from `IMG_GetError()` :
> JPEG images are not supported

This is done from [this](https://github.com/libsdl-org/SDL_image/blob/SDL-1.2/IMG_jpg.c#L471) function, that is only compiled when the macro `LOAD_JPG` is present, which is set [here](https://github.com/libsdl-org/SDL_image/blob/633dc522f5114f6d473c910dace62e8ca27a1f7d/configure#L13051). It appears that it would be necessary to provide `--enable-jpg` to the configure script in this case.

This is only an example for JPG. Any other file format support should be enabled the same way and the necessary options added. The full list can be seen here:
https://github.com/libsdl-org/SDL_image/blob/633dc522f5114f6d473c910dace62e8ca27a1f7d/configure#L1609
For reference, the old sdl-wii sets all of these macros manually

**Comment by WinterMute** [comment]
There was some kind of packaging error with wii-sdl_image.

For reference the non devkitPro packaged wii sdl was built incorrectly and has no bearing on this package. If you read the configure script you linked to all those options default to yes so the only reason to use `--enable-jpg` would be to explicitly disable jpeg decoding even if an appropriate library is found.

The package has been rebuilt and should now allow for jpeg & png support.
