### ISSUE TITLE
dkp-toolchain-vars: macOS zsh suddenly unhappy with ndsvars.sh

### ISSUE THREAD

**Issue by rhaleblian** [devkitPro/pacman-packages#290]
```
ray@metal dslibris % source /opt/devkitpro/ndsvars.sh
/opt/devkitpro/ndsvars.sh:.:1: no such file or directory: /devkitarm.sh
```
Not sure when this started, as it used to work.  I did do a package update today.

Maybe Apple decided something about `BASH_SOURCE%`.
I typically leverage `BASH_SOURCE[0]` to find a file's location, but am not sure how portable that is.

**Comment by rhaleblian** [comment]
A variation that works using the position variable; again edge cases and portability are topics. 
```
ray@metal dslibris % cat /opt/devkitpro/ndsvars.zsh 
. "$(dirname $(realpath $0))/devkitarm.sh"

PORTLIBS_PREFIX=${PORTLIBS_ROOT}/nds
PATH=$PORTLIBS_PREFIX/bin:$PATH

export CFLAGS="-march=armv5te -mtune=arm946e-s -O2 -ffunction-sections -fdata-sections"
export CXXFLAGS="${CFLAGS}"
export CPPFLAGS="-D__NDS__ -DARM9 -I${PORTLIBS_PREFIX}/include -I${DEVKITPRO}/libnds/include"
export LDFLAGS="-L${PORTLIBS_PREFIX}/lib -L${DEVKITPRO}/libnds/lib"
export LIBS="-lnds9"
```

**Comment by WinterMute** [comment]
Most straightforward way to deal with this is just to use the DEVKITPRO env variable instead of getting caught up in shell compatibility issues. https://github.com/devkitPro/pacman-packages/commit/c0c2536383d9b61efe04b288e50574269ded5172

**Comment by rhaleblian** [comment]
Also, it isn't really valid to use .sh code under zsh; you'll need to roll your own thing that will probably just do as per above.

**Comment by rhaleblian** [comment]
OK fine.  Best of luck to everybody!
