### ISSUE TITLE
re-adding psp-dev support in (dkp)-pacman

### ISSUE THREAD

**Issue by looni01** [devkitPro/pacman-packages#294]
Hi, 

I’ve read that devkitPro once (around 2005) supported the PSP but because there was not enough support it was discontinued. 

Since then there was quite some active development and the pspdev team made a great toolchain ( /pspdev/psptoolchain ) and a complete development environment ( /pspdev/pspdev ):
https://github.com/pspdev 

They even made a package manager for it: 
https://github.com/pspdev/psp-pacman 
https://github.com/pspdev/psp-packages 

I thought maybe you could be interested in re-adding it to your devkitPro_pacman? 
Would be great if everything could be installed & updated with one package manager again. :D 

Kind regards  
looni01

**Comment by WinterMute** [comment]
devkitPro supplied builds of the pspdev toolchain for a while before we started using pacman. It's unlikely that we would consider repackaging psp binaries & libraries without people willing to assist with packaging and support.
