### ISSUE TITLE
dkp-pacman error: devkitARM-r60-9-x86_64.pkg.tar.zst: Unrecognized archive format

### ISSUE THREAD

**Issue by laqieer** [devkitPro/pacman-packages#296]
I use the following command to update:
```
sudo dkp-pacman -Syu
```
Then error happens:
```
/opt/devkitpro/pacman/var/cache/pacman/pkg/devkitARM-r60-9-x86_64.pkg.tar.zst: Unrecognized archive format
```
And someone else is also facing the same problem [here](https://www.pokecommunity.com/showthread.php?p=10619684#post10619684).

**Comment by laqieer** [comment]
Current version of dkp-pacman:
```
dkp-pacman -V        

 .--.                  Pacman v5.0.1 - libalpm v10.0.1
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2017 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
```
However zstd is supported in pacman's higher version:
- https://archlinux.org/news/required-update-to-recent-libarchive/
- https://archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/
- https://gitlab.archlinux.org/pacman/pacman/-/blob/master/NEWS#L49

**Comment by WinterMute** [comment]
> Current version of dkp-pacman:

You have an old version installed. See https://github.com/devkitPro/pacman/releases/tag/v6.0.2 to get latest binaries
