### ISSUE TITLE
localtime not work after upgrade devkitA64

### ISSUE THREAD

**Issue by xfangfang** [devkitPro/pacman-packages#302]
# Issue

I am in the East Eighth Time Zone (UTC/GMT+08:00), but the time returned by `localtime` is UTC time.

You can use sample code to verify this issue: https://github.com/switchbrew/switch-examples/tree/master/time

# Analysis

It seems that this issue occurred after devkitA64 updated newlib to 4.3.0.

# Others

Due to this issue, I had to use an old version of the docker image to compile my homebrew app: `devkitpro/devkita64:20221113`

There is no problem with this old version.

# Another issue may related to this

In addition, when using the new version of devkitA64 with MPV, MPV may show a blue screen after playing the video for a while, which does not exist with the old version of devkitA64.

More precisely, in the version `20230526`, with [Cpasjuste's modified mpv](https://github.com/Cpasjuste/mpv/tree/switch), an error will appear after the blue screen. Here is the stack information:

```shell
# this is my code to call mpv to draw on the screen
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x24a7a0
0x000000000024a7a0: MPVCore::openglDraw(brls::Rect, float) at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7a2254
0x00000000007a2254: mpv_render_context_render at :?

# mpv internal calls
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7c08e4
0x00000000007c08e4: render at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7b0194
0x00000000007b0194: gl_video_render_frame at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7aed24
0x00000000007aed24: pass_draw_to_screen at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7ae78c
0x00000000007ae78c: pass_render_frame_dumb at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7a896c
0x00000000007a896c: copy_image at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x7ba9a0
0x00000000007ba9a0: gl_sc_addf at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x80fe48
0x000000000080fe48: bstr_xappend_vasprintf at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x14f3610
0x00000000014f3610: vsnprintf at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x14f3560
0x00000000014f3560: _vsnprintf_r at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x14ec9c0
0x00000000014ec9c0: _svfprintf_r at :?
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x1515c40
0x0000000001515c40: _dtoa_r at :?

# PC
$ aarch64-none-elf-addr2line -e wiliwili.elf -f -p -C -a 0x1517068
0x0000000001517068: _Balloc at :?

```

I'm not sure if the issue with MPV is related to devkitA64, but it does happen after the update.

Before the blue screen appeared, when the first video was interrupted and the second video was played, there would be noise, which did not exist before. This problem occurred after I updated the SDL, and I guess it may be caused by changes in switch-sdl2

Thank you to the maintainer !

**Comment by WinterMute** [comment]
localtime issue has been fixed in latest libnx & a new docker rolled. The mpv issue is most likely unrelated

**Comment by xfangfang** [comment]
@WinterMute 

Thank you for the quick fix. localtime is working.

I will submit another issue to report MPV related issues.
