### ISSUE TITLE
pacman.conf not found at install

### ISSUE THREAD

**Issue by oblerion** [devkitPro/pacman-packages#304]
Result of install devkitpro-pacman 
OS : Ubuntu 22.04.2 LTS

![Screenshot from 2023-05-28 10-40-18](https://github.com/devkitPro/pacman-packages/assets/82583559/9f7c9e75-335e-4e8e-a838-7d96f4be2953)

**Comment by WinterMute** [comment]
Can't reproduce that here. It looks like you may have tried to install over the residue of a previous installation?

Try completely removing /opt/devkitpro & installing again.

**Comment by oblerion** [comment]
Yes, I deleted but I forgot to purge the configuration.  
i do that : 
```sh 
sudo apt purge devkitpro-pacman
```
Now all work, thank for help.
