### ISSUE TITLE
Linker error in libSDL

### ISSUE THREAD

**Issue by mardy** [devkitPro/pacman-packages#316]
When building a program with the latest libSDL (`wii-sdl-1.2.15-11-any`) I get this link error:

```
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/portlibs/wii/lib/libSDL.a(SDL_ogcAudio.o): in function `OGC_AudioStart':
SDL_ogcAudio.c:(.text.OGC_AudioStart+0x44): undefined reference to `AESND_AllocateVoiceWithArg'
collect2: error: ld returned 1 exit status
```

This was not happening with 1.2.15-8, which I had installed before. Note also that I'm not using any audio functions in my program.

**Comment by oreo639** [comment]
What version of libogc do you have installed?

**Comment by WinterMute** [comment]
We don't support old versions of tools & libraries, sorry. Use (dkp-)pacman to reinstall the wii-dev group & report whatever problems need fixing with the versions we do support.
