### ISSUE TITLE
Possibly broken scanKeys()

### ISSUE THREAD

**Issue by dbeef** [devkitPro/pacman-packages#33]
I updated my devkitPro bundle a few hours ago using pacman, built my project (with no compiler errors after switching to new devkitPro version) and It won't register any X / Y button presses anymore. It still registers bumpers and B / A keys.

Before this I used devkitPro from ~February fetched from SourceForge (sorry but I don't know specific version number ).

File where I scan for input:
https://github.com/dbeef/spelunky-ds/blob/master/source/input/input_handler.cpp

It's same on both desmume and my NDS with moonshell.

**Comment by dbeef** [comment]
My packages (dkp-pacman -Sl) :

dkp-libs 3ds-bulletphysics 2.87-2
dkp-libs 3ds-bzip2 1.0.6-2
dkp-libs 3ds-curl 7.59.0-2
dkp-libs 3ds-examples 20180513-2
dkp-libs 3ds-flite 2.1-1
dkp-libs 3ds-freetype 2.9-1
dkp-libs 3ds-jansson 2.11-1
dkp-libs 3ds-libarchive 3.1.2-2
dkp-libs 3ds-libconfig 1.7.2-1
dkp-libs 3ds-libid3tag 0.15.1b-1
dkp-libs 3ds-libjpeg-turbo 1.5.3-1
dkp-libs 3ds-liblzma 5.2.3-1
dkp-libs 3ds-libmad 0.15.1b-1
dkp-libs 3ds-libogg 1.3.3-2
dkp-libs 3ds-libpng 1.6.34-1
dkp-libs 3ds-libvorbisidec 1.2.1-1
dkp-libs 3ds-mbedtls 2.8.0-1
dkp-libs 3ds-mikmod 3.3.11.1-1
dkp-libs 3ds-mpg123 1.25.10-1
dkp-libs 3ds-pkg-config 0.28-2
dkp-libs 3ds-sdl 1.2.15-1
dkp-libs 3ds-sdl_gfx 2.0.25-1
dkp-libs 3ds-sdl_image 1.2.12-1
dkp-libs 3ds-sdl_mixer 1.2.12-2
dkp-libs 3ds-sdl_ttf 2.0.11-1
dkp-libs 3ds-tinyxml2 6.0.0-1
dkp-libs 3ds-zlib 1.2.11-1
dkp-libs citro2d 1.0.0-1
dkp-libs citro3d 1.4.0-1
dkp-libs default-arm7 0.7.4-1 [installed]
dkp-libs devkitpro-pkgbuild-helpers 1.0.2-1
dkp-libs dswifi 0.4.2-1 [installed]
dkp-libs gamecube-examples 20180520-1
dkp-libs gba-examples 20170228-3
dkp-libs gp32-examples 20051021-2
dkp-libs libctru 1.5.0-1
dkp-libs libfat-gba 1.1.3-1
dkp-libs libfat-nds 1.1.3-1 [installed]
dkp-libs libfat-ogc 1.1.3-1
dkp-libs libfilesystem 0.9.14-1 [installed]
dkp-libs libgba 0.5.1-1
dkp-libs libmirko 0.9.8-1
dkp-libs libnds 1.7.2-1 [installed]
dkp-libs libnx 1.2.1-1
dkp-libs libogc 1.8.19-1
dkp-libs maxmod-gba 1.0.11-1
dkp-libs maxmod-nds 1.0.11-1 [installed]
dkp-libs nds-examples 20180516-2 [installed]
dkp-libs ppc-libjpeg-turbo 1.5.3-1
dkp-libs ppc-libogg 1.3.3-2
dkp-libs ppc-libpng 1.6.34-1
dkp-libs ppc-libvorbisidec 1.2.1-1
dkp-libs ppc-mpg123 1.25.10-1
dkp-libs ppc-mxml 2.11-1
dkp-libs ppc-pkg-config 0.28-3
dkp-libs ppc-zlib 1.2.11-1
dkp-libs switch-bulletphysics 2.87-1
dkp-libs switch-bzip2 1.0.6-2
dkp-libs switch-curl 7.59.0-1
dkp-libs switch-examples 20180522-1
dkp-libs switch-flac 1.3.2-1
dkp-libs switch-freetype 2.9-3
dkp-libs switch-libconfig 1.7.2-1
dkp-libs switch-libjpeg-turbo 1.5.3-1
dkp-libs switch-libmad 0.15.1b-1
dkp-libs switch-libmikmod 3.3.11.1-1
dkp-libs switch-libmodplug 0.8.8.5-1
dkp-libs switch-libogg 1.3.3-1
dkp-libs switch-libpng 1.6.34-3
dkp-libs switch-libsamplerate 0.1.9-1
dkp-libs switch-libvorbis 1.3.5-1
dkp-libs switch-libvorbisidec 1.2.1-1
dkp-libs switch-mpg123 1.25.10-2
dkp-libs switch-pkg-config 0.28-2
dkp-libs switch-sdl2 2.0.8-7
dkp-libs switch-sdl2_gfx 1.0.4-1
dkp-libs switch-sdl2_image 2.0.3-3
dkp-libs switch-sdl2_mixer 2.0.2-2
dkp-libs switch-sdl2_ttf 2.0.14-2
dkp-libs switch-zlib 1.2.11-1
dkp-libs wii-examples 20180520-1
dkp-linux 3dslink 0.5.2-2
dkp-linux 3dstools 1.1.4-2
dkp-linux devkit-env 1.0.1-1 [installed]
dkp-linux devkitA64 r10-2
dkp-linux devkitARM r49-2 [installed]
dkp-linux devkitPPC r31-2
dkp-linux devkitpro-keyring r1.787e015-2 [installed]
dkp-linux dstools 1.2.1-1 [installed]
dkp-linux gamecube-tools 1.0.2-1
dkp-linux gba-tools 1.1.0-1
dkp-linux general-tools 1.0.2-2 [installed]
dkp-linux gp32-tools 1.0.3-1
dkp-linux grit 0.8.15-1 [installed]
dkp-linux mmutil 1.8.7-1 [installed]
dkp-linux ndstool 2.1.2-1 [installed]
dkp-linux picasso 2.7.0-1
dkp-linux switch-tools 1.4.0-3
dkp-linux tex3ds 1.0.0-3
dkp-linux wiiload 0.5.1-1

**Comment by WinterMute** [comment]
not a pacman issue
