### ISSUE TITLE
[SDL_gfx] `rotateSurface90Degrees` returns a locked surface

### ISSUE THREAD

**Issue by mardy** [devkitPro/pacman-packages#331]
I just spent several hours debugging an issue with SDL, and finally discovered a bug in SDL_gfx: the function `rotateSurface90Degrees()` has a copy&paste error in its implementation, which causes it to lock the returned surface twice:

```c
	if (SDL_MUSTLOCK(dst)) {
		SDL_LockSurface(dst);
	}
	if (SDL_MUSTLOCK(dst)) {
		SDL_LockSurface(dst);
	}
```

(you can find this code [here](https://sourceforge.net/p/sdlgfx/code/HEAD/tree/SDL_rotozoom.c#l841)). Indeed, the author wanted to lock `dst` only once, and then to lock `src`. The end of the function has the respective calls to SDL_UnlockSurface().

I'm reporting this just to share the knowledge, in case someone bumps into this issue. I'm not sure if it's worth to write a patch for this. In any case, I've filed an upstream issue too: https://sourceforge.net/p/sdlgfx/bugs/16/ (assuming that the project is still alive)

**Comment by WinterMute** [comment]
Patched Wii & Gamecube packages pending update from upstream.

**Comment by mardy** [comment]
Hi Dave, could you please update the package to 2.0.27? The fix has been released (there's also another fix in the release :-) ).
