### ISSUE TITLE
License of CMake build scripts

### ISSUE THREAD

**Issue by neobrain** [devkitPro/pacman-packages#332]
Do the CMake build scripts under https://github.com/devkitPro/pacman-packages/tree/master/cmake come with any particular license?

It would be great to have an official license notice somewhere (either in the individual files or for the repository as a whole). I would hope in particular it's something permissive like MIT, since GPL would complicate licensing of any 3DS homebrew that uses these CMake scripts as part of its build process.

Cheers!

**Comment by WinterMute** [comment]
Even if we were to make the cmakery "all rights reserved" it would have no impact on the licensing of 3DS homebrew that used them as part of their build process. If copyright worked how you're implying here then Microsoft would own any code you wrote for windows using one of their proprietary compilers.

**Comment by WinterMute** [comment]
Just to be absolutely clear here. Using scripts we wrote to compile your homebrew gives us no rights over your code.

> > Even if we were to make the cmakery "all rights reserved" it would have no impact on the licensing of 3DS homebrew that used them as part of their build process. If copyright worked how you're implying here then Microsoft would own any code you wrote for windows using one of their proprietary compilers.
> 
> The GPL for example has explicit provisions regarding build systems for source distributions. I think it's probably fine, but why not make it clear from the get-go?
> 
> If I'm reading between the lines correctly it sounds like you don't have any particular preference here. Does that mean you consider the repo content public domain?

No. We mean that using scripts we wrote to compile your homebrew gives us no rights over your code including whatever scripts you use that may use the features from our cmakery as intended. This does not however give you the right to distribute scripts we wrote without our permission.

If you have some use case you believe is unfairly impacted then do feel free to drop us a line on support@devkitpro.org
