### ISSUE TITLE
Can't connect to devkitpro servers because my IP has been banned?

### ISSUE THREAD

**Issue by parknich** [devkitPro/pacman-packages#344]
## Bug Report
[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>
[ Note: If you include links to websites who promote and encourage intellectual property infringment then those links and references to them will be removed. People who persistently include such links and/or argue about their removal will be blocked; ]</br>
No it is not.

### What's the issue you encountered?
Cannot access the devkitpro site or update devkitpro in MSYS2 because my IP has been banned for some reason
[ Describe the issue in detail and what you were doing beforehand. ]</br>
Trying to update devkitpro
[ Did you make any changes related to devkitPro tooling? ]</br>
No
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?
Ban your ip address?
[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Environment?

- What host OS are you using?
  - it can be useful for us to see the output from env.txt on your system. Please redact any personal information.
  - For windows users we often find that use of cmd shell or powershell to be the source of the problem. Please use the supplied msys2 shell.
- Official release or unofficial/self-compiled build: 
  - Please note we only support binaries we supplied. We'll do our best but unfortunately all too often problems with self compiled tools and/or libraries can not be replicated with those distributed via our pacman repos.

Windows, MSYS2. mingw64
### Additional context?
 I am unsure why, my IP seems to have been banned from devkitpro.org and wintermutes personal site, I have no idea why. And so I cant use devkitpro, I really need to be able to use it, so please consider unbanning my IP, I can send you my IP
- Additional info about your environment:
Home internet connection
I'm the only one that would be using devkitpro
- [ Any other information relevant to your issue. ]

**Comment by WinterMute** [comment]
Send your IP to support@devkitpro.org & we'll have a look.

**Comment by WinterMute** [comment]
Presuming this has been resolved due to lack of response.
