### ISSUE TITLE
Issue with ARM7 define in GBA cmake and libfat

### ISSUE THREAD

**Issue by Lorenzooone** [devkitPro/pacman-packages#348]
Here the cmake defines ARM7 for the GBA cmake: https://github.com/devkitPro/pacman-packages/blob/013a75724f85af383c229c33c4b251b43c954952/cmake/gba/NintendoGBA.cmake#L16
However, libfat checks for ARM7 to define __NDS__ in its header, which then causes issues when its tries to include ds-specific files here:
https://github.com/devkitPro/libfat/blob/154f7829d43421754085877d533d66743d42619a/include/fat.h#L43

**Comment by endrift** [comment]
I filed https://github.com/devkitPro/libfat/pull/25 to take care of it in libfat instead of the cmake toolchains.

**Comment by Lorenzooone** [comment]
Okay, sounds good.
I was kind of worried that this define could have problematic interactions with other libraries as well. But if that is not the case, changing libfat only should suffice.

Closing the issue for now. Thanks!
