### ISSUE TITLE
gamecube-sdl2_image missing from dkp-libs

### ISSUE THREAD

**Issue by Mode8fx** [devkitPro/pacman-packages#350]
### What's the issue you encountered?

Gamecube's `sdl2_image` library is currently missing from dkp-libs. The other SDL2 libraries are present; only image is missing.

### How can the issue be reproduced?

N/A

### Environment?

N/A

### Additional context?

N/A

**Comment by WinterMute** [comment]
added with https://github.com/devkitPro/pacman-packages/commit/0134cf0622e31c6706bbe5fdb4fcb698bbe9dfd5
