### ISSUE TITLE
Blocked From devkitpro.org

### ISSUE THREAD

**Issue by unkn0wncvm1** [devkitPro/pacman-packages#351]
Hello, I Was Gonna Try Getting The devkitPro packages when i tried to enter devkitpro.org i couldnt access the website saying: Error 1006 Access Denied. Is There Way To Get Unblocked?

**Comment by WinterMute** [comment]
We can't help unless you tell us your IP address. Email support@devkitpro.org if you want it kept private.

**Comment by unkn0wncvm1** [comment]
UPDATE:My IP Address Got Unbanned and Now I Can enter the website and receive packages ffrom the dkp-linux repo

**Comment by unkn0wncvm1** [comment]
somehow i got rebanned
