### ISSUE TITLE
switch-zziplib is pulling an empty package

### ISSUE THREAD

**Issue by ppkantorski** [devkitPro/pacman-packages#357]
## Bug Report

```
sudo dkp-pacman -S switch-zziplib
resolving dependencies...
looking for conflicting packages...

Packages (1) switch-zziplib-0.13.76-1

Total Download Size:  0.00 MiB
Total Removed Size:   0.30 MiB

```

### What's the issue you encountered?

The latest zziplib is completely empty.  Installing removes zziplib completely from dkp-pacman

### How can the issue be reproduced?

`sudo dkp-pacman -S switch-zziplib`

### Environment?

Apple M1, macOS Sonoma 14.2.1, latest dkp-pacman

**Comment by WinterMute** [comment]
This has surfaced a kind of odd issue with newlib that we're currently sorting out. The proper fix will need rebuilding toolchain and some other portlibs so it will take a little while. Hopefully later today.

**Comment by WinterMute** [comment]
fixed with https://github.com/devkitPro/pacman-packages/commit/04e07b5395fd70effa74be3e3a628793c7fd05d6
