### ISSUE TITLE
Switch-sdl2 function redefinition

### ISSUE THREAD

**Issue by Oreo639** [devkitPro/pacman-packages#49]
Im getting a function redefinition error with SDL_LoadFunction and SDL_UnloadObject.
```/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.2.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/portlibs/switch/lib/libSDL2.a(SDL_sysloadso.o): in function `SDL_LoadFunction':
/home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.8/src/loadso/dummy/SDL_sysloadso.c:42: multiple definition of `SDL_LoadFunction'; /opt/devkitpro/portlibs/switch/lib/libSDL2.a(SDL_switchopengles.o):/home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.8/src/video/switch/SDL_switchopengles.c:65: first defined here
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.2.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/portlibs/switch/lib/libSDL2.a(SDL_sysloadso.o): in function `SDL_UnloadObject':
/home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.8/src/loadso/dummy/SDL_sysloadso.c:50: multiple definition of `SDL_UnloadObject'; /opt/devkitpro/portlibs/switch/lib/libSDL2.a(SDL_switchopengles.o):/home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.8/src/video/switch/SDL_switchopengles.c:71: first defined here```

**Comment by Cpasjuste** [comment]
Should be fixed in #22

**Comment by Oreo639** [comment]
Thx. I'll close once it is merged and the package here is updated.
