### ISSUE TITLE
SSL port for the switch

### ISSUE THREAD

**Issue by xavo95** [devkitPro/pacman-packages#50]
I see that libcurl is compiled both without ssl and http2 support, letting http2 aside. When I compiled openssl.

When I set up the flag of ssl in curl configure it fails(i will provide more details).

Also why the switch didn't get a mbedtls port like 3ds?

Regards

**Comment by xavo95** [comment]
Releated to the mbedtls branch.

Will test in the following days

**Comment by gjimenezf** [comment]
Please could you add support for ssl https. This is required for Tinfoil: https://github.com/digableinc/tinfoil/issues/8

**Comment by rsn8887** [comment]
If this is done, will it provide libcrypto?

**Comment by psfree** [comment]
This is a pretty damn important thing for switch apps that go online. Any ideas how it may be possible to fix? I tried to do a a custom cross build of ssl libraries with curl but it didn't work.

**Comment by xavo95** [comment]
Sorry for the several months delay I was involved on another projects, I will catch up asap

**Comment by xavo95** [comment]
[mbed-tls](https://github.com/devkitPro/pacman-packages/tree/mbedtls)

**Comment by D-rex0** [comment]
I have managed to build the Curl package from the mbed-tls tree.
But if fails at handshake : "Connection reset by peer"

**Comment by WinterMute** [comment]
> I have managed to build the Curl package from the mbed-tls tree.
> But if fails at handshake : "Connection reset by peer"

We know. This is why it isn't currently available. 

Why are you all obsessed with this?

**Comment by gjimenezf** [comment]
Because it allows homebrew to connect to Google drive and many others that only support https.
I saw that SX Installer support https, so they are using their own SDK with https support.

**Comment by WinterMute** [comment]
They're not using their own SDK. They're using a bodge to bypass the error we're currently trying to fix.

**Comment by gjimenezf** [comment]
Wouldn't a good idea to do the same until a proper fix is ready?

**Comment by WinterMute** [comment]
Bodges have a terrible habit of being left to rot & cause issues elsewhere which become difficult to mitigate.

devkitPro and the Switchbrew team have a reputation for taking the long term view, we don't do short sighted & inappropriate bodges just to get stuff working. 

I wish more people understood just how much work goes into building an infrastructure like this and keeping it maintainable. Please exercise patience, we'll get there in the end.

**Comment by D-rex0** [comment]
I totally understand you.
I just gave a shot, because I thought SX had stolen your code..

**Comment by D-rex0** [comment]
Just to point out some weird stuff I've found out...
Since I'm not a professional programmer and I'm too lazy to find out how to enable the Mbedtls debbuger, I've just added a "printf" right at the  beginning of the mbedtls_ssl_handshake_step function. The weird thing is that it finished the handshake, but failed to start downloading.
As I said, I'm not a professional... 
Since printf adds nothing, but a delay, would it be a "timing" issue?

**Comment by D-rex0** [comment]
Got it working, in this hackish way... Any idea how to solve this for real?

**Comment by WinterMute** [comment]
Getting it solved for real will go much faster if people aren't constantly mithering about bodges ...

Be patient and don't spread bodges. It does more damage in the long term.

**Comment by D-rex0** [comment]
First of all, thank you so much for your work!
I understand your point of view (and deleted my post).
People are not impatient with you, but with the collateral damage.
There is a bodge business going on. People are making money out of bodges!
I know you don't want to support piracy, but this makes the worse kind of pirates to get into the game.
I just wanted to help... I'm sorry.

**Comment by blawar** [comment]
Keep up the good work @WinterMute , I appreciate the work you do.  The bodge has no reported bugs currently, works great.

**Comment by WinterMute** [comment]
ssl support now enabled with latest libcurl package, supported by latest libnx.
