### ISSUE TITLE
devkitpro-pkgbuild-helpers issue with cmake

### ISSUE THREAD

**Issue by Oreo639** [devkitPro/pacman-packages#60]
When I try to compile cmake packages it fails.
I will be using the 3ds as an example however it is not limited to it.
I get an error
```
CMake Error at /usr/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/oreo639/git/pacman-packages/3ds/TinyXML2/src/tinyxml2-6.0.0/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_3ff76/fast"
    /usr/bin/make -f CMakeFiles/cmTC_3ff76.dir/build.make CMakeFiles/cmTC_3ff76.dir/build
    make[1]: Entering directory '/home/oreo639/git/pacman-packages/3ds/TinyXML2/src/tinyxml2-6.0.0/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_3ff76.dir/testCCompiler.c.o
    /opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc   -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -O2 -mword-relocations -ffunction-sections -fdata-sections -D_3DS -I /opt/devkitpro/portlibs/3ds/include -I /opt/devkitpro/libctru/include    -o CMakeFiles/cmTC_3ff76.dir/testCCompiler.c.o   -c /home/oreo639/git/pacman-packages/3ds/TinyXML2/src/tinyxml2-6.0.0/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_3ff76
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3ff76.dir/link.txt --verbose=1
    /opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -O2 -mword-relocations -ffunction-sections -fdata-sections -D_3DS -I /opt/devkitpro/portlibs/3ds/include -I /opt/devkitpro/libctru/include   -L/opt/devkitpro/portlibs/3ds/lib -L/opt/devkitpro/libctru/lib  -rdynamic CMakeFiles/cmTC_3ff76.dir/testCCompiler.c.o  -o cmTC_3ff76 
    arm-none-eabi-gcc: error: unrecognized command line option '-rdynamic'
    make[1]: *** [CMakeFiles/cmTC_3ff76.dir/build.make:87: cmTC_3ff76] Error 1
    make[1]: Leaving directory '/home/oreo639/git/pacman-packages/3ds/TinyXML2/src/tinyxml2-6.0.0/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_3ff76/fast] Error 2
```
This can be fixed by removing
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -specs=3dsx.specs")
fromand changing include(devkitarm.cmake) to include(/opt/devkitpro/devkitarm.cmake)
in 3ds.cmake. Is this intentional or am I doing something wrong?
(ofc you also have to change devkitarm.cmake, in the PKGBUILD, to 3ds.cmake but that is a different issue)

**Comment by Oreo639** [comment]
Ok, so the include paths were fixed. However I still get the same errors I showed while 
`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -specs=3dsx.specs")`
is still there for whatever reason.

**Comment by WinterMute** [comment]
Will need more information on what you're trying to build.

Bear in mind that we recommend installing packages via (dkp-)pacman rather than building these packages manually. We also don't recommend cmake for general use because it's a big giant PiTA for cross compiling, especially for a bare metal environment. The primary reason we have these toolchain files is for building packages that require cmake and have no alternative build system.

**Comment by WinterMute** [comment]
Then the discussion would be better on the wildmidi PR instead of causing confusion here.

cmake is enough of a pain as it is without wondering why you're getting errors that don't occur on build machines.
