### ISSUE TITLE
jansson unavailable

### ISSUE THREAD

**Issue by Steveice10** [devkitPro/pacman-packages#7]
I've been using jansson from 3ds_portlibs in FBI for reading and writing JSON files, however it doesn't seem to be available in the new pacman repository. Since 3ds_portlibs is now deprecated, could this be added back?

**Comment by Cpasjuste** [comment]
Hi @Steveice10 , added a PR for that #9

**Comment by WinterMute** [comment]
and now available through (dkp-)pacman, use -Syy to sync dbs
