### ISSUE TITLE
trying to compile scummvm    Missing CPP compiler

### ISSUE THREAD

**Issue by fennectech** [devkitPro/pacman-packages#80]
I have devkitpro instaled but i keep getting this
[fennectech@Aluminum ~/scummvm]$  ./configure --host=switch --backend=switch 
Running ScummVM configure...
Looking for C++ compiler... none found!

**Comment by WinterMute** [comment]
You don't have devkitPro installed, we are an organisation who provide tools and libraries for homebrew console development.

The issue tracker for our pacman packages repository is also not a suitable place for this kind of support.

See https://devkitpro.org/wiki/Community_Portal for ways to contact us.

**Comment by rsn8887** [comment]
The Switch port hasn’t been merged into mainline ScummVM yet.

To compile ScummVM using latest git  source plus all the Switch code from the switch_new_pr branch:

- rebase the ScummVM upstream master onto switch_new_pr branch

- PKG_CONFIG_PATH=$DEVKITPRO/portlibs/switch/lib/pkgconfig ../scummvm/configure --host=switch --disable-debug --enable-all-engines --disable-engine=testbed --enable-optimizations

**Comment by rsn8887** [comment]
Wintermute you are adding an extra hurdle by recommending Xchat on the https://devkitpro.org/wiki/Community_Portal  page, which is not free for Windows. It is quite expensive for an irc client. There are many free alternatives for Windows.

**Comment by fennectech** [comment]
Thank you for this.   Ive managed to compile everything myself from the information in the PR

**Comment by WinterMute** [comment]
@rsn8887 recommending that people use docker images not provided by us on our own issue tracker is seriously out of order. There was a reason why I pointed to the community portal page rather than discussing things here and you've now subverted that.

I've updated the page to point to hexchat instead though. Thanks for pointing that out.

**Comment by rsn8887** [comment]
Oh sorry. The docker image provided by you would also work in this case I think. The only thing I changed was to add cmake. But ScummVM doesn't need cmake.

**Comment by WinterMute** [comment]
> Oh sorry. The docker image provided by you would also work in this case I think. The only thing I changed was to add cmake. But ScummVM doesn't need cmake.

Yes but you've taken away the opportunity for us to work with someone having trouble with the tools and figure out ways to improve how things work. Please don't answer issues on our trackers without first checking with us.

**Comment by rsn8887** [comment]
Again I apologize. I honestly just wanted to help since I have recently worked-on and compiled ScummVM without problems. I didn't want to take away any opportunities.

**Comment by fennectech** [comment]
Well i still have the issue with my natively installed setup. I have devkitpro and devkita64 as i can compile other switch binaries.  I’m quite confident my issues came from user error specific to ScummVM Its my fault for asking in the wrong repo.   I’m probably missing an dependency.

**Comment by DevanWolf** [comment]
Same for me on Windows 7.
