### ISSUE TITLE
Package devkit-env not included in group wiiu-dev

### ISSUE THREAD

**Issue by jakobkg** [devkitPro/pacman-packages#89]
The package 'devkit-env', which helpfully adds a few environment variables and appends the devkitPro-provided tool binaries to PATH, seems to be missing from the group wiiu-dev. The package is included in all the other groups listed on the [devkitPro pacman wiki page](https://devkitpro.org/wiki/devkitPro_pacman#Predefined_Groups) such as switch-dev and nds-dev, which makes its exclusion from the wiiu-dev group seem like an oversight.

**Comment by WinterMute** [comment]
Wrong repo for this issue but never mind. Fixed with https://github.com/devkitPro/tool-packages/commit/444510550374f237386560fe848a41f83767d88b
